# Generated by Django 5.0.2 on 2025-06-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('PRIVATE', 'Private Room'), ('CONFERENCE', 'Conference Room'), ('SHARED', 'Shared Desk')], max_length=15)),
                ('capacity', models.PositiveIntegerField()),
                ('room_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
